/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

/**
 *
 * @author under
 */
public class Seleccion extends javax.swing.JFrame {
    int maletin;

    /**
     * Creates new form Seleccion
     */
    public Seleccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbd1 = new javax.swing.JRadioButton();
        rbd2 = new javax.swing.JRadioButton();
        rbd3 = new javax.swing.JRadioButton();
        rbd4 = new javax.swing.JRadioButton();
        rbd5 = new javax.swing.JRadioButton();
        rbd6 = new javax.swing.JRadioButton();
        rbd7 = new javax.swing.JRadioButton();
        rbd8 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rbd10 = new javax.swing.JRadioButton();
        rbd11 = new javax.swing.JRadioButton();
        rbd12 = new javax.swing.JRadioButton();
        rbd14 = new javax.swing.JRadioButton();
        rbd13 = new javax.swing.JRadioButton();
        rbd15 = new javax.swing.JRadioButton();
        rbd16 = new javax.swing.JRadioButton();
        rbd17 = new javax.swing.JRadioButton();
        rbd18 = new javax.swing.JRadioButton();
        rbd19 = new javax.swing.JRadioButton();
        rbd20 = new javax.swing.JRadioButton();
        rbd21 = new javax.swing.JRadioButton();
        rbd22 = new javax.swing.JRadioButton();
        rbd23 = new javax.swing.JRadioButton();
        rbd24 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 0));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Selecciona tu maletin");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel1.setBackground(new java.awt.Color(153, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        buttonGroup1.add(rbd1);
        rbd1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd1.setText("1");
        rbd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd1.setBorderPainted(true);

        buttonGroup1.add(rbd2);
        rbd2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd2.setText("2");
        rbd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd2.setBorderPainted(true);
        rbd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbd3);
        rbd3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd3.setText("3");
        rbd3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd3.setBorderPainted(true);
        rbd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbd4);
        rbd4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd4.setText("4");
        rbd4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd4.setBorderPainted(true);

        buttonGroup1.add(rbd5);
        rbd5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd5.setText("5");
        rbd5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd5.setBorderPainted(true);

        buttonGroup1.add(rbd6);
        rbd6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd6.setText("6");
        rbd6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd6.setBorderPainted(true);

        buttonGroup1.add(rbd7);
        rbd7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd7.setText("7");
        rbd7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd7.setBorderPainted(true);

        buttonGroup1.add(rbd8);
        rbd8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd8.setText("8");
        rbd8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd8.setBorderPainted(true);

        buttonGroup1.add(rb9);
        rb9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb9.setText("9");
        rb9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rb9.setBorderPainted(true);

        buttonGroup1.add(rbd10);
        rbd10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd10.setText("10");
        rbd10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd10.setBorderPainted(true);

        buttonGroup1.add(rbd11);
        rbd11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd11.setText("11");
        rbd11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd11.setBorderPainted(true);

        buttonGroup1.add(rbd12);
        rbd12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd12.setText("12");
        rbd12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd12.setBorderPainted(true);

        buttonGroup1.add(rbd14);
        rbd14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd14.setText("14");
        rbd14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd14.setBorderPainted(true);
        rbd14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd14ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbd13);
        rbd13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd13.setText("13");
        rbd13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd13.setBorderPainted(true);
        rbd13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd13ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbd15);
        rbd15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd15.setText("15");
        rbd15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd15.setBorderPainted(true);
        rbd15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd15ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbd16);
        rbd16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd16.setText("16");
        rbd16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd16.setBorderPainted(true);

        buttonGroup1.add(rbd17);
        rbd17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd17.setText("17");
        rbd17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd17.setBorderPainted(true);
        rbd17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd17ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbd18);
        rbd18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd18.setText("18");
        rbd18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd18.setBorderPainted(true);

        buttonGroup1.add(rbd19);
        rbd19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd19.setText("19");
        rbd19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd19.setBorderPainted(true);

        buttonGroup1.add(rbd20);
        rbd20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd20.setText("20");
        rbd20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd20.setBorderPainted(true);

        buttonGroup1.add(rbd21);
        rbd21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd21.setText("21");
        rbd21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd21.setBorderPainted(true);

        buttonGroup1.add(rbd22);
        rbd22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd22.setText("22");
        rbd22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd22.setBorderPainted(true);

        buttonGroup1.add(rbd23);
        rbd23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd23.setText("23");
        rbd23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd23.setBorderPainted(true);

        buttonGroup1.add(rbd24);
        rbd24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbd24.setText("24");
        rbd24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rbd24.setBorderPainted(true);
        rbd24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd24ActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rb9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbd1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbd17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbd2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbd10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbd18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbd11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbd12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbd13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbd14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbd15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbd16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbd3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbd4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbd5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbd6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbd7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbd8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbd19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbd20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbd21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbd22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbd23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbd24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb9)
                            .addComponent(rbd10)
                            .addComponent(rbd11)
                            .addComponent(rbd12)
                            .addComponent(rbd13)
                            .addComponent(rbd14)
                            .addComponent(rbd15)
                            .addComponent(rbd16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbd1)
                            .addComponent(rbd2)
                            .addComponent(rbd3)
                            .addComponent(rbd4)
                            .addComponent(rbd5)
                            .addComponent(rbd6)
                            .addComponent(rbd7)
                            .addComponent(rbd8))))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbd17)
                    .addComponent(rbd18)
                    .addComponent(rbd19)
                    .addComponent(rbd20)
                    .addComponent(rbd21)
                    .addComponent(rbd22)
                    .addComponent(rbd23)
                    .addComponent(rbd24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbd2ActionPerformed

    private void rbd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbd3ActionPerformed

    private void rbd14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbd14ActionPerformed

    private void rbd15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbd15ActionPerformed

    private void rbd13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbd13ActionPerformed

    private void rbd17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbd17ActionPerformed

    private void rbd24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbd24ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        if(rbd1.isSelected()){
          maletin=1;
      }
        if(rbd2.isSelected()){
          maletin=2;
      }
        if(rbd3.isSelected()){
          maletin=3;
      }
        if(rbd4.isSelected()){
          maletin=4;
      }
        if(rbd5.isSelected()){
          maletin=5;
      }
        if(rbd6.isSelected()){
          maletin=6;
      }
        if(rbd7.isSelected()){
          maletin=7;
      }
        if(rbd8.isSelected()){
          maletin=8;
      }
        if(rb9.isSelected()){
          maletin=9;
      }
        if(rbd10.isSelected()){
          maletin=10;
      }
        if(rbd11.isSelected()){
          maletin=11;
      }
        if(rbd12.isSelected()){
          maletin=12;
      }
        if(rbd13.isSelected()){
          maletin=13;
      }
        if(rbd14.isSelected()){
          maletin=14;
      }
        if(rbd15.isSelected()){
          maletin=15;
      }
        if(rbd16.isSelected()){
          maletin=16;
      }
        if(rbd17.isSelected()){
          maletin=17;
      }
        if(rbd18.isSelected()){
          maletin=18;
      }
        if(rbd19.isSelected()){
          maletin=19;
      }
        if(rbd20.isSelected()){
          maletin=20;
      }
        if(rbd21.isSelected()){
          maletin=21;
      }
        if(rbd22.isSelected()){
          maletin=22;
      }
        if(rbd23.isSelected()){
          maletin=23;
      }
        if(rbd24.isSelected()){
          maletin=24;
      }
       /*Juego abrir=new Juego();
       abrir.setVisible(true);
       this.setVisible(false);*/
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb9;
    private javax.swing.JRadioButton rbd1;
    private javax.swing.JRadioButton rbd10;
    private javax.swing.JRadioButton rbd11;
    private javax.swing.JRadioButton rbd12;
    private javax.swing.JRadioButton rbd13;
    private javax.swing.JRadioButton rbd14;
    private javax.swing.JRadioButton rbd15;
    private javax.swing.JRadioButton rbd16;
    private javax.swing.JRadioButton rbd17;
    private javax.swing.JRadioButton rbd18;
    private javax.swing.JRadioButton rbd19;
    private javax.swing.JRadioButton rbd2;
    private javax.swing.JRadioButton rbd20;
    private javax.swing.JRadioButton rbd21;
    private javax.swing.JRadioButton rbd22;
    private javax.swing.JRadioButton rbd23;
    private javax.swing.JRadioButton rbd24;
    private javax.swing.JRadioButton rbd3;
    private javax.swing.JRadioButton rbd4;
    private javax.swing.JRadioButton rbd5;
    private javax.swing.JRadioButton rbd6;
    private javax.swing.JRadioButton rbd7;
    private javax.swing.JRadioButton rbd8;
    // End of variables declaration//GEN-END:variables
}
